#!/bin/bash
XD_HOME=~/spring-xd
./gradlew build
cp modules/processor/*.xml $XD_HOME/xd/modules/processor
cp scripts/hashtags.groovy $XD_HOME/xd/modules/processor/scripts
cp hashtag-analyzer/build/libs/hashtag-analyzer.jar $XD_HOME/xd/lib
cp hashtag-analyzer/build/libs/hashtag-analyzer.jar $XD_HOME/gemfire/lib
cp config/twitter-demo.xml $XD_HOME/gemfire/config