#! /bin/sh
PORT=8080
if [ x"$1" != x ]; then
	PORT=$1
fi
URL="http://localhost:$PORT"
PWD=`pwd`

FILE="$PWD/../data/twitter.out"

#Create main ingest stream
curl -v -H "Accept: application/json" -d name=tweets2 -d definition="tail --name=$FILE --fromEnd=false+%7C+ log" "$URL/streams"
curl -v -H "Accept: application/json" -X PUT -d deploy=false "$URL/streams/tweets2"

#Set up a gemfire tap
curl -v -H "Accept: application/json" -d name=hashtags -d definition="tap@tweets2+%7C+json-to-tuple+%7C+filter --script=hashtags.groovy+%7C+tweetToMap+%7C+gemfire-server --regionName=hashtags --keyExpression=payload['id']" "$URL/taps"

#curl -v -H "Accept: application/json" -d name=tweetlang -d definition="tap@tweets2+%7C+field-value-counter --fieldName=lang" "$URL/taps"

curl -v -H "Accept: application/json" -X PUT -d deploy=true "$URL/streams/tweets2"